// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Font } from "./Font";
import type { Look } from "./Look";
import type { Theme } from "./Theme";

/**
 * Everything the settings need, and the look in force.
 */
export type Appearance = { look: Look, themes: Array<Theme>, fonts: Array<Font>, 
/**
 * The first family of the editor font VS Code or a fork is set to, when one is set.
 */
editorFont: string | null, 
/**
 * Something the settings have to say, such as a theme file that could not be read.
 */
message: string | null, };
