// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The open blank takes the typed answer; a mirror repeats it at another occurrence of the
 * same name, since one answer substitutes every one.
 */
export type Blank = "input" | "mirror";
