// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Run } from "./Run";

/**
 * The next line being written: the current one with the chosen node blanked out.
 */
export type Draft = { runs: Array<Run>, input: string, };
