// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Catalog } from "./Catalog";
import type { CourseView } from "./CourseView";
import type { Draft } from "./Draft";
import type { Feedback } from "./Feedback";
import type { Run } from "./Run";
import type { Written } from "./Written";

export type EvaluationView = { course: CourseView, catalog: Catalog, bindings: Array<string>, history: Array<Written>, current: Array<Run>, 
/**
 * The run indices, first and last, each selectable node covers.
 */
extents: Record<number, [number, number]>, 
/**
 * The node the student pointed at with the keyboard or a click, while no blank is open.
 */
selected: number | null, draft: Draft | null, 
/**
 * How the question ended: its value, or the sub-expression that raised and what.
 */
ending: string | null, feedback: Feedback, message: string | null, };
