// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a face comes from.
 */
export type FontPick = { "kind": "skin" } | { "kind": "editor" } | { "kind": "family", family: string, };
