// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An installed family the student may pick.
 */
export type Font = { family: string, monospace: boolean, 
/**
 * Whether it draws every logic symbol a formula may hold (∧ ∨ → ↔ ¬ ⊥); `None` where it
 * was not checked.
 */
logic: boolean | null, };
