// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Catalog } from "./Catalog";
import type { CourseView } from "./CourseView";
import type { Feedback } from "./Feedback";
import type { ProofLineView } from "./ProofLineView";

export type ProofView = { course: CourseView, catalog: Catalog, goal: string, lines: Array<ProofLineView>, 
/**
 * How many assumptions are open: the depth the next line is written at.
 */
open: number, finished: boolean, input: string, feedback: Feedback, 
/**
 * The line the feedback judged, while that verdict is the last word.
 */
judged: number | null, rules: string | null, message: string | null, };
