// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Blank } from "./Blank";

/**
 * One stretch of the rendered expression owned by one node, or by none.
 */
export type Run = { text: string, node: number | null, blank: Blank | null, };
