// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A line of the question's record above the line in hand.
 */
export type Written = { "kind": "expression", "text": string } | { "kind": "taken-back", "text": string };
