// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Listed } from "./Listed";

/**
 * The questions the student may pick from, in order.
 */
export type Catalog = { title: string, questions: Array<Listed>, current: number | null, };
