// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the question in hand sits in the course.
 */
export type CourseView = { language: string, title: string, 
/**
 * The set's title while a set opened from a file is walked in order.
 */
set: string | null, position: number, 
/**
 * How many questions an ordered set holds; random practice never runs out.
 */
count: number | null, back: boolean, forward: boolean, };
