// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Choosing a language, before any question is open.
 */
export type EntryView = { 
/**
 * The title of a question set opened from a file, which the chosen language walks.
 */
set: string | null, message: string | null, };
