// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontPick } from "./FontPick";

/**
 * The look a student chose. Saved by the shell beside the progress file.
 */
export type Look = { 
/**
 * A built-in skin's id, which the page owns, or the id of one of [`Appearance::themes`].
 */
skin: string, 
/**
 * The face for prose: headers, feedback, buttons.
 */
prose: FontPick, 
/**
 * The face for formulas and proof lines.
 */
formula: FontPick, };
