// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProofLineView = { number: number, depth: number, formula: string, rule: string, references: Array<number>, premise: boolean, assumption: boolean, };
