// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A colour theme from the editor ecosystem, turned into the roles this window draws with.
 */
export type Theme = { 
/**
 * Stable across launches: where it came from and its label, so a saved look finds it again.
 */
id: string, name: string, 
/**
 * Where it was found, for the settings list: "VS Code", "Cursor", "导入" and so on.
 */
source: string, dark: boolean, 
/**
 * Values for the page's role tokens, keyed by the custom property's name without `--`:
 * surface, ink, ink-faded, ink-bright, mark-write, mark-wrong, mark-point, mark-good,
 * quiet-mark, tray, scrollbar, focus-ring, ink-glow.
 */
tokens: { [key in string]: string }, };
