// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryView } from "./EntryView";
import type { EvaluationView } from "./EvaluationView";
import type { ProofView } from "./ProofView";

/**
 * One screen of the window.
 */
export type View = { "kind": "entry" } & EntryView | { "kind": "evaluation" } & EvaluationView | { "kind": "proof" } & ProofView;
